version: 2

jobs:
  deploy-dev:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
      - run: sudo apt-get install jq
      - run: ls
      - run: ./build deploy dev us-east-1
      - run: ./build tune dev us-east-1 balanced

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only: master
